# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: |
          rm -rf arnotes.github.io &&
          git clone "https://${gituser}:${gitpass}@github.com/arnotes/arnotes.github.io.git" arnotes.github.io &&
          rm -rf ./arnotes.github.io/static &&
          rm -rf ./arnotes.github.io/bootstrap.css &&
          rm -rf ./arnotes.github.io/favicon.ico &&
          rm -rf ./arnotes.github.io/index.html &&
          rm -rf ./arnotes.github.io/manifest.json &&
          rm -rf ./arnotes.github.io/precache-manifest.*.js &&
          rm -rf ./arnotes.github.io/service-worker.js &&
          rm -rf ./arnotes.github.io/asset-manifest.json &&
          npm run build &&
          cp -R build/* ./arnotes.github.io/
      
      - run : |
          git config user.email "${gitemail}" &&
          git config user.name "${gituser}" &&
          cd arnotes.github.io &&
          git add . &&
          git commit -m "CircleCI Deploy - $(date)" &&
          git push       

        
