export enum ActionTypes {
  SET_USER = 'SET_USER',
  SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE',
  SET_NOTE_LIST = 'SET_NOTE_LIST',
  SET_FOLDER_LIST = 'SET_FOLDER_LIST',
  SET_FILTERED_NOTE_LIST = 'SET_FILTERED_NOTE_LIST',
  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
  SET_SELECTED_NOTE = 'SET_SELECTED_NOTE',
  SET_SEARCHINPUT_FOCUS_STATE = 'SET_SEARCHINPUT_FOCUS_STATE'
}